from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import time

# Définir le navigateur à utiliser
driver = webdriver.Chrome(ChromeDriverManager().install())

url = 'https://hudoc.echr.coe.int/fre#{« sort": ["respondentOrderFre%20Ascending"],"languageisocode":["FRE"],"respondent": ["FRA"],"documentcollectionid2":["GRANDCHAMBER","CHAMBER"],"violation": ["2","2-1","3","4","4-1","4-2","5","5-1","5-1-c","5-1-e","5-1-f","5-2","5-3","5-4","5-5","6","6+6-3","6+6-3-c","6+13","6-1","6-1+6-3-a","6-1+6-3-b","6-1+6-3-c","6-1+6-3-d","6-2","6-3","6-3-a","6-3-b","6-3-c","6-3-c+6-1","6-3-d","7","7-1","8","8-1","8-2","9","9-1","10","10-1","11","13","14"]}'
driver.get(url)

# Attendre que la page se charge complètement
wait = WebDriverWait(driver, 10)
wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="CASELAW"]/span/input')))

jurisprudence = driver.find_element_by_xpath('//*[@id="CASELAW"]/span/input')
jurisprudence.click()
grandeChambre = driver.find_element_by_xpath('//*[@id="GRANDCHAMBER"]/span/input')
grandeChambre.click()
Chambre = driver.find_element_by_xpath('//*[@id="CHAMBER"]/span/input')
Chambre.click()
time.sleep(5)



element = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="refinement-filters-row1-left"]/div/div/div[3]/button')))
driver.execute_script("arguments[0].scrollIntoView();", element)
plusLangueFrancais = driver.find_element_by_xpath('//*[@id="refinement-filters-row1-left"]/div/div/div[3]/button')
plusLangueFrancais.click()
clickFrancais1 = driver.find_element_by_xpath('//*[@id="FRE"]/input')
clickFrancais1.click()
OK = driver.find_element_by_xpath('//*[@id="okbutton"]')
OK.click()
Francais = driver.find_element_by_xpath('//*[@id="refinement-filters-row2-left"]/div/div/div[3]/button')
Francais.click()
clickFrancais2 = driver.find_element_by_xpath('//*[@id="FRA"]/input')
clickFrancais2.click()
OK = driver.find_element_by_xpath('//*[@id="okbutton"]')
OK.click()
time.sleep(5)


element = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="refinement-filters-row3-right"]/div/div/div[3]/button')))
driver.execute_script("arguments[0].scrollIntoView();", element)

violation = driver.find_element_by_xpath('//*[@id="refinement-filters-row3-right"]/div/div/div[3]/button')
violation.click()

violationX = driver.find_element_by_xpath('//*[@id="2"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="2-1"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="3"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="4"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="4-1"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="4-2"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="5"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="5-1"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="5-1-c"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="5-1-e"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="5-1-f"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="5-2"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="5-3"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="5-4"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="5-5"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6+6-3"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6+6-3-c"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6+13"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-1"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-1+6-3-a"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-1+6-3-b"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-1+6-3-c"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-1+6-3-d"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-2"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-3"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-3-a"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-3-b"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-3-c"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-3-c+6-1"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="6-3-d"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="7"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="7-1"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="8"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="8-1"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="8-2"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="9"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="9-1"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="10"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="10-1"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="11"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="13"]/input')
violationX.click()
violationX = driver.find_element_by_xpath('//*[@id="14"]/input')
violationX.click()

OK = driver.find_element_by_xpath('//*[@id="okbutton"]')
OK.click()